using Microsoft.Win32;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace scout
{
    class Helpers
    {
        public static string COMPUTERNAME;

        public static RegistryKey GetRegistryKey(string hive, string path)
        {
            if (hive == "HKCU")
            {
                return RegistryKey.OpenRemoteBaseKey(RegistryHive.CurrentUser, COMPUTERNAME).OpenSubKey(path);
            }
            else if (hive == "HKU")
            {
                return RegistryKey.OpenRemoteBaseKey(RegistryHive.Users, COMPUTERNAME).OpenSubKey(path);
            }
            else
            {
                return RegistryKey.OpenRemoteBaseKey(RegistryHive.LocalMachine, COMPUTERNAME).OpenSubKey(path);
            }
        }

        public static string GetRegValue(string hive, string path, string value)
        {
            // returns a single registry value under the specified path in the specified hive (HKLM/HKCU)
            string regKeyValue = "";
            var regKey = GetRegistryKey(hive, path);
            if (regKey != null)
            {
                regKeyValue = String.Format("{0}", regKey.GetValue(value));
            }
            return regKeyValue;
        }

        public static byte[] GetRegValueBytes(string hive, string path, string value)
        {
            // returns a byte array of single registry value under the specified path in the specified hive (HKLM/HKCU)
            byte[] regKeyValue = null;
            var regKey = GetRegistryKey(hive, path);
            if (regKey != null)
            {
                regKeyValue = (byte[])regKey.GetValue(value);
            }
            return regKeyValue;
        }

        public static Dictionary<string, object> GetRegValues(string hive, string path)
        {
            // returns all registry values under the specified path in the specified hive (HKLM/HKCU)
            Dictionary<string, object> keyValuePairs = null;
            try
            {
                using (var regKeyValues = GetRegistryKey(hive, path))
                {
                    if (regKeyValues != null)
                    {
                        var valueNames = regKeyValues.GetValueNames();
                        keyValuePairs = valueNames.ToDictionary(name => name, regKeyValues.GetValue);
                    }
                }
                return keyValuePairs;
            }
            catch
            {
                return null;
            }
        }

        public static string[] GetRegSubkeys(string hive, string path)
        {
            // returns an array of the subkeys names under the specified path in the specified hive (HKLM/HKCU/HKU)
            try
            {
                RegistryKey myKey = GetRegistryKey(hive, path);
                String[] subkeyNames = myKey.GetSubKeyNames();
                return myKey.GetSubKeyNames();
            }
            catch
            {
                return new string[0];
            }
        }


        // from https://github.com/GhostPack/Seatbelt/blob/master/Seatbelt/Program.cs#L3274 which is in turn
        // from https://github.com/threatexpress/red-team-scripts/blob/master/HostEnum.ps1#L985-L1033
        public static Hashtable InterestingProcesses = new Hashtable(StringComparer.InvariantCultureIgnoreCase)
            {
                {"mcshield"                        , "McAfee AV"},
                {"windefend"                       , "Windows Defender AV"},
                {"MSASCui"                         , "Windows Defender AV"},
                {"MSASCuiL"                        , "Windows Defender AV"},
                {"msmpeng"                         , "Windows Defender AV"},
                {"msmpsvc"                         , "Windows Defender AV"},
                {"WRSA"                            , "WebRoot AV"},
                {"savservice"                      , "Sophos AV"},
                {"TMCCSF"                          , "Trend Micro AV"},
                {"symantec antivirus"              , "Symantec AV"},
                {"mbae"                            , "MalwareBytes Anti-Exploit"},
                {"parity"                          , "Bit9 application whitelisting"},
                {"cb"                              , "Carbon Black behavioral analysis"},
                {"bds-vision"                      , "BDS Vision behavioral analysis"},
                {"Triumfant"                       , "Triumfant behavioral analysis"},
                {"CSFalcon"                        , "CrowdStrike Falcon EDR"},
                {"ossec"                           , "OSSEC intrusion detection"},
                {"TmPfw"                           , "Trend Micro firewall"},
                {"dgagent"                         , "Verdasys Digital Guardian DLP"},
                {"kvoop"                           , "Unknown DLP process" },
                {"AAWTray"                         , "Possible Defensive Proccess"},
                {"ackwin32"                        , "Possible Defensive Proccess"},
                {"Ad-Aware"                        , "Possible Defensive Proccess"},
                {"adaware"                         , "Possible Defensive Proccess"},
                {"advxdwin"                        , "Possible Defensive Proccess"},
                {"agentsvr"                        , "Possible Defensive Proccess"},
                {"agentw"                          , "Possible Defensive Proccess"},
                {"alertsvc"                        , "Possible Defensive Proccess"},
                {"alevir"                          , "Possible Defensive Proccess"},
                {"alogserv"                        , "Possible Defensive Proccess"},
                {"amon9x"                          , "Possible Defensive Proccess"},
                {"anti-trojan"                     , "Possible Defensive Proccess"},
                {"antivirus"                       , "Possible Defensive Proccess"},
                {"ants"                            , "Possible Defensive Proccess"},
                {"apimonitor"                      , "Possible Defensive Proccess"},
                {"aplica32"                        , "Possible Defensive Proccess"},
                {"apvxdwin"                        , "Possible Defensive Proccess"},
                {"arr"                             , "Possible Defensive Proccess"},
                {"atcon"                           , "Possible Defensive Proccess"},
                {"atguard"                         , "Possible Defensive Proccess"},
                {"atro55en"                        , "Possible Defensive Proccess"},
                {"atupdater"                       , "Possible Defensive Proccess"},
                {"atwatch"                         , "Possible Defensive Proccess"},
                {"au"                              , "Possible Defensive Proccess"},
                {"aupdate"                         , "Possible Defensive Proccess"},
                {"auto-protect.nav80try"           , "Possible Defensive Proccess"},
                {"autodown"                        , "Possible Defensive Proccess"},
                {"autoruns"                        , "Possible Defensive Proccess"},
                {"autorunsc"                       , "Possible Defensive Proccess"},
                {"autotrace"                       , "Possible Defensive Proccess"},
                {"autoupdate"                      , "Possible Defensive Proccess"},
                {"avconsol"                        , "Possible Defensive Proccess"},
                {"ave32"                           , "Possible Defensive Proccess"},
                {"avgcc32"                         , "Possible Defensive Proccess"},
                {"avgctrl"                         , "Possible Defensive Proccess"},
                {"avgemc"                          , "Possible Defensive Proccess"},
                {"avgnt"                           , "Possible Defensive Proccess"},
                {"avgrsx"                          , "Possible Defensive Proccess"},
                {"avgserv"                         , "Possible Defensive Proccess"},
                {"avgserv9"                        , "Possible Defensive Proccess"},
                {"avguard"                         , "Possible Defensive Proccess"},
                {"avgwdsvc"                        , "Possible Defensive Proccess"},
                {"avgui"                           , "Possible Defensive Proccess"},
                {"avgw"                            , "Possible Defensive Proccess"},
                {"avkpop"                          , "Possible Defensive Proccess"},
                {"avkserv"                         , "Possible Defensive Proccess"},
                {"avkservice"                      , "Possible Defensive Proccess"},
                {"avkwctl9"                        , "Possible Defensive Proccess"},
                {"avltmain"                        , "Possible Defensive Proccess"},
                {"avnt"                            , "Possible Defensive Proccess"},
                {"avp"                             , "Possible Defensive Proccess"},
                {"avp32"                           , "Possible Defensive Proccess"},
                {"avpcc"                           , "Possible Defensive Proccess"},
                {"avpdos32"                        , "Possible Defensive Proccess"},
                {"avpm"                            , "Possible Defensive Proccess"},
                {"avptc32"                         , "Possible Defensive Proccess"},
                {"avpupd"                          , "Possible Defensive Proccess"},
                {"avsched32"                       , "Possible Defensive Proccess"},
                {"avsynmgr"                        , "Possible Defensive Proccess"},
                {"avwin"                           , "Possible Defensive Proccess"},
                {"avwin95"                         , "Possible Defensive Proccess"},
                {"avwinnt"                         , "Possible Defensive Proccess"},
                {"avwupd"                          , "Possible Defensive Proccess"},
                {"avwupd32"                        , "Possible Defensive Proccess"},
                {"avwupsrv"                        , "Possible Defensive Proccess"},
                {"avxmonitor9x"                    , "Possible Defensive Proccess"},
                {"avxmonitornt"                    , "Possible Defensive Proccess"},
                {"avxquar"                         , "Possible Defensive Proccess"},
                {"backweb"                         , "Possible Defensive Proccess"},
                {"bargains"                        , "Possible Defensive Proccess"},
                {"bd_professional"                 , "Possible Defensive Proccess"},
                {"beagle"                          , "Possible Defensive Proccess"},
                {"belt"                            , "Possible Defensive Proccess"},
                {"bidef"                           , "Possible Defensive Proccess"},
                {"bidserver"                       , "Possible Defensive Proccess"},
                {"bipcp"                           , "Possible Defensive Proccess"},
                {"bipcpevalsetup"                  , "Possible Defensive Proccess"},
                {"bisp"                            , "Possible Defensive Proccess"},
                {"blackd"                          , "Possible Defensive Proccess"},
                {"blackice"                        , "Possible Defensive Proccess"},
                {"blink"                           , "Possible Defensive Proccess"},
                {"blss"                            , "Possible Defensive Proccess"},
                {"bootconf"                        , "Possible Defensive Proccess"},
                {"bootwarn"                        , "Possible Defensive Proccess"},
                {"borg2"                           , "Possible Defensive Proccess"},
                {"bpc"                             , "Possible Defensive Proccess"},
                {"brasil"                          , "Possible Defensive Proccess"},
                {"bs120"                           , "Possible Defensive Proccess"},
                {"bundle"                          , "Possible Defensive Proccess"},
                {"bvt"                             , "Possible Defensive Proccess"},
                {"ccapp"                           , "Possible Defensive Proccess"},
                {"ccevtmgr"                        , "Possible Defensive Proccess"},
                {"ccpxysvc"                        , "Possible Defensive Proccess"},
                {"ccSvcHst"                        , "Possible Defensive Proccess"},
                {"cdp"                             , "Possible Defensive Proccess"},
                {"cfd"                             , "Possible Defensive Proccess"},
                {"cfgwiz"                          , "Possible Defensive Proccess"},
                {"cfiadmin"                        , "Possible Defensive Proccess"},
                {"cfiaudit"                        , "Possible Defensive Proccess"},
                {"cfinet"                          , "Possible Defensive Proccess"},
                {"cfinet32"                        , "Possible Defensive Proccess"},
                {"claw95"                          , "Possible Defensive Proccess"},
                {"claw95cf"                        , "Possible Defensive Proccess"},
                {"clean"                           , "Possible Defensive Proccess"},
                {"cleaner"                         , "Possible Defensive Proccess"},
                {"cleaner3"                        , "Possible Defensive Proccess"},
                {"cleanpc"                         , "Possible Defensive Proccess"},
                {"cleanup"                         , "Possible Defensive Proccess"},
                {"click"                           , "Possible Defensive Proccess"},
                {"cmdagent"                        , "Possible Defensive Proccess"},
                {"cmesys"                          , "Possible Defensive Proccess"},
                {"cmgrdian"                        , "Possible Defensive Proccess"},
                {"cmon016"                         , "Possible Defensive Proccess"},
                {"connectionmonitor"               , "Possible Defensive Proccess"},
                {"cpd"                             , "Possible Defensive Proccess"},
                {"cpf9x206"                        , "Possible Defensive Proccess"},
                {"cpfnt206"                        , "Possible Defensive Proccess"},
                {"ctrl"                            , "Possible Defensive Proccess"},
                {"cv"                              , "Possible Defensive Proccess"},
                {"cwnb181"                         , "Possible Defensive Proccess"},
                {"cwntdwmo"                        , "Possible Defensive Proccess"},
                {"CylanceUI"                       , "Possible Defensive Proccess"},
                {"CyProtect"                       , "Possible Defensive Proccess"},
                {"CyUpdate"                        , "Possible Defensive Proccess"},
                {"cyserver"                        , "Possible Defensive Proccess"},
                {"cytray"                          , "Possible Defensive Proccess"},
                {"CyveraService"                   , "Possible Defensive Proccess"},
                {"datemanager"                     , "Possible Defensive Proccess"},
                {"dcomx"                           , "Possible Defensive Proccess"},
                {"defalert"                        , "Possible Defensive Proccess"},
                {"defscangui"                      , "Possible Defensive Proccess"},
                {"defwatch"                        , "Possible Defensive Proccess"},
                {"deputy"                          , "Possible Defensive Proccess"},
                {"divx"                            , "Possible Defensive Proccess"},
                {"dgprompt"                        , "Possible Defensive Proccess"},
                {"DgService"                       , "Possible Defensive Proccess"},
                {"dllcache"                        , "Possible Defensive Proccess"},
                {"dllreg"                          , "Possible Defensive Proccess"},
                {"doors"                           , "Possible Defensive Proccess"},
                {"dpf"                             , "Possible Defensive Proccess"},
                {"dpfsetup"                        , "Possible Defensive Proccess"},
                {"dpps2"                           , "Possible Defensive Proccess"},
                {"drwatson"                        , "Possible Defensive Proccess"},
                {"drweb32"                         , "Possible Defensive Proccess"},
                {"drwebupw"                        , "Possible Defensive Proccess"},
                {"dssagent"                        , "Possible Defensive Proccess"},
                {"dumpcap"                         , "Possible Defensive Proccess"},
                {"dvp95"                           , "Possible Defensive Proccess"},
                {"dvp95_0"                         , "Possible Defensive Proccess"},
                {"ecengine"                        , "Possible Defensive Proccess"},
                {"efpeadm"                         , "Possible Defensive Proccess"},
                {"egui"                            , "Possible Defensive Proccess"},
                {"ekrn"                            , "Possible Defensive Proccess"},
                {"emet_agent"                      , "Possible Defensive Proccess"},
                {"emet_service"                    , "Possible Defensive Proccess"},
                {"emsw"                            , "Possible Defensive Proccess"},
                {"engineserver"                    , "Possible Defensive Proccess"},
                {"ent"                             , "Possible Defensive Proccess"},
                {"esafe"                           , "Possible Defensive Proccess"},
                {"escanhnt"                        , "Possible Defensive Proccess"},
                {"escanv95"                        , "Possible Defensive Proccess"},
                {"espwatch"                        , "Possible Defensive Proccess"},
                {"ethereal"                        , "Possible Defensive Proccess"},
                {"etrustcipe"                      , "Possible Defensive Proccess"},
                {"evpn"                            , "Possible Defensive Proccess"},
                {"exantivirus-cnet"                , "Possible Defensive Proccess"},
                {"exe.avxw"                        , "Possible Defensive Proccess"},
                {"expert"                          , "Possible Defensive Proccess"},
                {"explore"                         , "Possible Defensive Proccess"},
                {"f-agnt95"                        , "Possible Defensive Proccess"},
                {"f-prot"                          , "Possible Defensive Proccess"},
                {"f-prot95"                        , "Possible Defensive Proccess"},
                {"f-stopw"                         , "Possible Defensive Proccess"},
                {"fameh32"                         , "Possible Defensive Proccess"},
                {"fast"                            , "Possible Defensive Proccess"},
                {"fch32"                           , "Possible Defensive Proccess"},
                {"fcagswd"                         , "McAfee DLP Agent"},
                {"fcags"                           , "McAfee DLP Agent"},
                {"fih32"                           , "Possible Defensive Proccess"},
                {"findviru"                        , "Possible Defensive Proccess"},
                {"firesvc"                         , "McAfee Host Intrusion Prevention"},
                {"firetray"                        , "Possible Defensive Proccess"},
                {"firewall"                        , "Possible Defensive Proccess"},
                {"fnrb32"                          , "Possible Defensive Proccess"},
                {"fp-win"                          , "Possible Defensive Proccess"},
                {"fp-win_trial"                    , "Possible Defensive Proccess"},
                {"fprot"                           , "Possible Defensive Proccess"},
                {"frameworkservice"                , "Possible Defensive Proccess"},
                {"frminst"                         , "Possible Defensive Proccess"},
                {"frw"                             , "Possible Defensive Proccess"},
                {"fsaa"                            , "Possible Defensive Proccess"},
                {"fsav"                            , "Possible Defensive Proccess"},
                {"fsav32"                          , "Possible Defensive Proccess"},
                {"fsav530stbyb"                    , "Possible Defensive Proccess"},
                {"fsav530wtbyb"                    , "Possible Defensive Proccess"},
                {"fsav95"                          , "Possible Defensive Proccess"},
                {"fsgk32"                          , "Possible Defensive Proccess"},
                {"fsm32"                           , "Possible Defensive Proccess"},
                {"fsma32"                          , "Possible Defensive Proccess"},
                {"fsmb32"                          , "Possible Defensive Proccess"},
                {"gator"                           , "Possible Defensive Proccess"},
                {"gbmenu"                          , "Possible Defensive Proccess"},
                {"gbpoll"                          , "Possible Defensive Proccess"},
                {"generics"                        , "Possible Defensive Proccess"},
                {"gmt"                             , "Possible Defensive Proccess"},
                {"guard"                           , "Possible Defensive Proccess"},
                {"guarddog"                        , "Possible Defensive Proccess"},
                {"hacktracersetup"                 , "Possible Defensive Proccess"},
                {"hbinst"                          , "Possible Defensive Proccess"},
                {"hbsrv"                           , "Possible Defensive Proccess"},
                {"HijackThis"                      , "Possible Defensive Proccess"},
                {"hipsvc"                          , "Possible Defensive Proccess"},
                {"HipMgmt"                         , "McAfee Host Intrusion Protection"},
                {"hotactio"                        , "Possible Defensive Proccess"},
                {"hotpatch"                        , "Possible Defensive Proccess"},
                {"htlog"                           , "Possible Defensive Proccess"},
                {"htpatch"                         , "Possible Defensive Proccess"},
                {"hwpe"                            , "Possible Defensive Proccess"},
                {"hxdl"                            , "Possible Defensive Proccess"},
                {"hxiul"                           , "Possible Defensive Proccess"},
                {"iamapp"                          , "Possible Defensive Proccess"},
                {"iamserv"                         , "Possible Defensive Proccess"},
                {"iamstats"                        , "Possible Defensive Proccess"},
                {"ibmasn"                          , "Possible Defensive Proccess"},
                {"ibmavsp"                         , "Possible Defensive Proccess"},
                {"icload95"                        , "Possible Defensive Proccess"},
                {"icloadnt"                        , "Possible Defensive Proccess"},
                {"icmon"                           , "Possible Defensive Proccess"},
                {"icsupp95"                        , "Possible Defensive Proccess"},
                {"icsuppnt"                        , "Possible Defensive Proccess"},
                {"iedll"                           , "Possible Defensive Proccess"},
                {"iedriver"                        , "Possible Defensive Proccess"},
                {"iface"                           , "Possible Defensive Proccess"},
                {"ifw2000"                         , "Possible Defensive Proccess"},
                {"inetlnfo"                        , "Possible Defensive Proccess"},
                {"infus"                           , "Possible Defensive Proccess"},
                {"infwin"                          , "Possible Defensive Proccess"},
                {"init"                            , "Possible Defensive Proccess"},
                {"intdel"                          , "Possible Defensive Proccess"},
                {"intren"                          , "Possible Defensive Proccess"},
                {"iomon98"                         , "Possible Defensive Proccess"},
                {"istsvc"                          , "Possible Defensive Proccess"},
                {"jammer"                          , "Possible Defensive Proccess"},
                {"jdbgmrg"                         , "Possible Defensive Proccess"},
                {"jedi"                            , "Possible Defensive Proccess"},
                {"kavlite40eng"                    , "Possible Defensive Proccess"},
                {"kavpers40eng"                    , "Possible Defensive Proccess"},
                {"kavpf"                           , "Possible Defensive Proccess"},
                {"kazza"                           , "Possible Defensive Proccess"},
                {"keenvalue"                       , "Possible Defensive Proccess"},
                {"kerio-pf-213-en-win"             , "Possible Defensive Proccess"},
                {"kerio-wrl-421-en-win"            , "Possible Defensive Proccess"},
                {"kerio-wrp-421-en-win"            , "Possible Defensive Proccess"},
                {"kernel32"                        , "Possible Defensive Proccess"},
                {"KeyPass"                         , "Possible Defensive Proccess"},
                {"killprocesssetup161"             , "Possible Defensive Proccess"},
                {"launcher"                        , "Possible Defensive Proccess"},
                {"ldnetmon"                        , "Possible Defensive Proccess"},
                {"ldpro"                           , "Possible Defensive Proccess"},
                {"ldpromenu"                       , "Possible Defensive Proccess"},
                {"ldscan"                          , "Possible Defensive Proccess"},
                {"lnetinfo"                        , "Possible Defensive Proccess"},
                {"loader"                          , "Possible Defensive Proccess"},
                {"localnet"                        , "Possible Defensive Proccess"},
                {"lockdown"                        , "Possible Defensive Proccess"},
                {"lockdown2000"                    , "Possible Defensive Proccess"},
                {"lookout"                         , "Possible Defensive Proccess"},
                {"lordpe"                          , "Possible Defensive Proccess"},
                {"lsetup"                          , "Possible Defensive Proccess"},
                {"luall"                           , "Possible Defensive Proccess"},
                {"luau"                            , "Possible Defensive Proccess"},
                {"lucomserver"                     , "Possible Defensive Proccess"},
                {"luinit"                          , "Possible Defensive Proccess"},
                {"luspt"                           , "Possible Defensive Proccess"},
                {"mapisvc32"                       , "Possible Defensive Proccess"},
                {"masvc"                           , "McAfee Agent"},
                {"mbamservice"                     , "Possible Defensive Proccess"},
                {"mcafeefire"                      , "Possible Defensive Proccess"},
                {"mcagent"                         , "Possible Defensive Proccess"},
                {"mcmnhdlr"                        , "Possible Defensive Proccess"},
                {"mcscript"                        , "Possible Defensive Proccess"},
                {"mcscript_inuse"                  , "Possible Defensive Proccess"},
                {"mctool"                          , "Possible Defensive Proccess"},
                {"mctray"                          , "Possible Defensive Proccess"},
                {"mcupdate"                        , "Possible Defensive Proccess"},
                {"mcvsrte"                         , "Possible Defensive Proccess"},
                {"mcvsshld"                        , "Possible Defensive Proccess"},
                {"md"                              , "Possible Defensive Proccess"},
                {"mfeann"                          , "McAfee VirusScan Enterprise"},
                {"mfemactl"                        , "McAfee VirusScan Enterprise"},
                {"mfevtps"                         , "Possible Defensive Proccess"},
                {"mfin32"                          , "Possible Defensive Proccess"},
                {"mfw2en"                          , "Possible Defensive Proccess"},
                {"mfweng3.02d30"                   , "Possible Defensive Proccess"},
                {"mgavrtcl"                        , "Possible Defensive Proccess"},
                {"mgavrte"                         , "Possible Defensive Proccess"},
                {"mghtml"                          , "Possible Defensive Proccess"},
                {"mgui"                            , "Possible Defensive Proccess"},
                {"minilog"                         , "Possible Defensive Proccess"},
                {"minionhost"                      , "Possible Defensive Proccess"},
                {"mmod"                            , "Possible Defensive Proccess"},
                {"monitor"                         , "Possible Defensive Proccess"},
                {"moolive"                         , "Possible Defensive Proccess"},
                {"mostat"                          , "Possible Defensive Proccess"},
                {"mpfagent"                        , "Possible Defensive Proccess"},
                {"mpfservice"                      , "Possible Defensive Proccess"},
                {"mpftray"                         , "Possible Defensive Proccess"},
                {"mrflux"                          , "Possible Defensive Proccess"},
                {"msapp"                           , "Possible Defensive Proccess"},
                {"msbb"                            , "Possible Defensive Proccess"},
                {"msblast"                         , "Possible Defensive Proccess"},
                {"mscache"                         , "Possible Defensive Proccess"},
                {"msccn32"                         , "Possible Defensive Proccess"},
                {"mscman"                          , "Possible Defensive Proccess"},
                {"msconfig"                        , "Possible Defensive Proccess"},
                {"msdm"                            , "Possible Defensive Proccess"},
                {"msdos"                           , "Possible Defensive Proccess"},
                {"msiexec16"                       , "Possible Defensive Proccess"},
                {"msinfo32"                        , "Possible Defensive Proccess"},
                {"mslaugh"                         , "Possible Defensive Proccess"},
                {"msmgt"                           , "Possible Defensive Proccess"},
                {"msmsgri32"                       , "Possible Defensive Proccess"},
                {"MsSense"                         , "Microsoft Defender ATP"},
                {"mssmmc32"                        , "Possible Defensive Proccess"},
                {"mssys"                           , "Possible Defensive Proccess"},
                {"msvxd"                           , "Possible Defensive Proccess"},
                {"mu0311ad"                        , "Possible Defensive Proccess"},
                {"mwatch"                          , "Possible Defensive Proccess"},
                {"n32scanw"                        , "Possible Defensive Proccess"},
                {"naprdmgr"                        , "Possible Defensive Proccess"},
                {"nav"                             , "Possible Defensive Proccess"},
                {"navap.navapsvc"                  , "Possible Defensive Proccess"},
                {"navapsvc"                        , "Possible Defensive Proccess"},
                {"navapw32"                        , "Possible Defensive Proccess"},
                {"navdx"                           , "Possible Defensive Proccess"},
                {"navlu32"                         , "Possible Defensive Proccess"},
                {"navnt"                           , "Possible Defensive Proccess"},
                {"navstub"                         , "Possible Defensive Proccess"},
                {"navw32"                          , "Possible Defensive Proccess"},
                {"navwnt"                          , "Possible Defensive Proccess"},
                {"nc2000"                          , "Possible Defensive Proccess"},
                {"ncinst4"                         , "Possible Defensive Proccess"},
                {"ndd32"                           , "Possible Defensive Proccess"},
                {"neomonitor"                      , "Possible Defensive Proccess"},
                {"neowatchlog"                     , "Possible Defensive Proccess"},
                {"netarmor"                        , "Possible Defensive Proccess"},
                {"netd32"                          , "Possible Defensive Proccess"},
                {"netinfo"                         , "Possible Defensive Proccess"},
                {"netmon"                          , "Possible Defensive Proccess"},
                {"netscanpro"                      , "Possible Defensive Proccess"},
                {"netspyhunter-1.2"                , "Possible Defensive Proccess"},
                {"netstat"                         , "Possible Defensive Proccess"},
                {"netutils"                        , "Possible Defensive Proccess"},
                {"nisserv"                         , "Possible Defensive Proccess"},
                {"nisum"                           , "Possible Defensive Proccess"},
                {"nmain"                           , "Possible Defensive Proccess"},
                {"nod32"                           , "Possible Defensive Proccess"},
                {"normist"                         , "Possible Defensive Proccess"},
                {"norton_internet_secu_3.0_407"    , "Possible Defensive Proccess"},
                {"notstart"                        , "Possible Defensive Proccess"},
                {"npf40_tw_98_nt_me_2k"            , "Possible Defensive Proccess"},
                {"npfmessenger"                    , "Possible Defensive Proccess"},
                {"nprotect"                        , "Possible Defensive Proccess"},
                {"npscheck"                        , "Possible Defensive Proccess"},
                {"npssvc"                          , "Possible Defensive Proccess"},
                {"nsched32"                        , "Possible Defensive Proccess"},
                {"nssys32"                         , "Possible Defensive Proccess"},
                {"nstask32"                        , "Possible Defensive Proccess"},
                {"nsupdate"                        , "Possible Defensive Proccess"},
                {"nt"                              , "Possible Defensive Proccess"},
                {"ntrtscan"                        , "Possible Defensive Proccess"},
                {"ntvdm"                           , "Possible Defensive Proccess"},
                {"ntxconfig"                       , "Possible Defensive Proccess"},
                {"nui"                             , "Possible Defensive Proccess"},
                {"nupgrade"                        , "Possible Defensive Proccess"},
                {"nvarch16"                        , "Possible Defensive Proccess"},
                {"nvc95"                           , "Possible Defensive Proccess"},
                {"nvsvc32"                         , "Possible Defensive Proccess"},
                {"nwinst4"                         , "Possible Defensive Proccess"},
                {"nwservice"                       , "Possible Defensive Proccess"},
                {"nwtool16"                        , "Possible Defensive Proccess"},
                {"nxlog"                           , "Possible Defensive Proccess"},
                {"ollydbg"                         , "Possible Defensive Proccess"},
                {"onsrvr"                          , "Possible Defensive Proccess"},
                {"optimize"                        , "Possible Defensive Proccess"},
                {"ostronet"                        , "Possible Defensive Proccess"},
                {"osqueryd"                        , "Possible Defensive Proccess"},
                {"otfix"                           , "Possible Defensive Proccess"},
                {"outpost"                         , "Possible Defensive Proccess"},
                {"outpostinstall"                  , "Possible Defensive Proccess"},
                {"outpostproinstall"               , "Possible Defensive Proccess"},
                {"padmin"                          , "Possible Defensive Proccess"},
                {"panixk"                          , "Possible Defensive Proccess"},
                {"patch"                           , "Possible Defensive Proccess"},
                {"pavcl"                           , "Possible Defensive Proccess"},
                {"pavproxy"                        , "Possible Defensive Proccess"},
                {"pavsched"                        , "Possible Defensive Proccess"},
                {"pavw"                            , "Possible Defensive Proccess"},
                {"pccwin98"                        , "Possible Defensive Proccess"},
                {"pcfwallicon"                     , "Possible Defensive Proccess"},
                {"pcip10117_0"                     , "Possible Defensive Proccess"},
                {"pcscan"                          , "Possible Defensive Proccess"},
                {"pdsetup"                         , "Possible Defensive Proccess"},
                {"periscope"                       , "Possible Defensive Proccess"},
                {"persfw"                          , "Possible Defensive Proccess"},
                {"perswf"                          , "Possible Defensive Proccess"},
                {"pf2"                             , "Possible Defensive Proccess"},
                {"pfwadmin"                        , "Possible Defensive Proccess"},
                {"pgmonitr"                        , "Possible Defensive Proccess"},
                {"pingscan"                        , "Possible Defensive Proccess"},
                {"platin"                          , "Possible Defensive Proccess"},
                {"pop3trap"                        , "Possible Defensive Proccess"},
                {"poproxy"                         , "Possible Defensive Proccess"},
                {"popscan"                         , "Possible Defensive Proccess"},
                {"portdetective"                   , "Possible Defensive Proccess"},
                {"portmonitor"                     , "Possible Defensive Proccess"},
                {"powerscan"                       , "Possible Defensive Proccess"},
                {"ppinupdt"                        , "Possible Defensive Proccess"},
                {"pptbc"                           , "Possible Defensive Proccess"},
                {"ppvstop"                         , "Possible Defensive Proccess"},
                {"prizesurfer"                     , "Possible Defensive Proccess"},
                {"prmt"                            , "Possible Defensive Proccess"},
                {"prmvr"                           , "Possible Defensive Proccess"},
                {"procdump"                        , "Possible Defensive Proccess"},
                {"processmonitor"                  , "Possible Defensive Proccess"},
                {"procexp"                         , "Possible Defensive Proccess"},
                {"procexp64"                       , "Possible Defensive Proccess"},
                {"procexplorerv1.0"                , "Possible Defensive Proccess"},
                {"procmon"                         , "Possible Defensive Proccess"},
                {"programauditor"                  , "Possible Defensive Proccess"},
                {"proport"                         , "Possible Defensive Proccess"},
                {"protectx"                        , "Possible Defensive Proccess"},
                {"pspf"                            , "Possible Defensive Proccess"},
                {"purge"                           , "Possible Defensive Proccess"},
                {"qconsole"                        , "Possible Defensive Proccess"},
                {"qserver"                         , "Possible Defensive Proccess"},
                {"rapapp"                          , "Possible Defensive Proccess"},
                {"rav7"                            , "Possible Defensive Proccess"},
                {"rav7win"                         , "Possible Defensive Proccess"},
                {"rav8win32eng"                    , "Possible Defensive Proccess"},
                {"ray"                             , "Possible Defensive Proccess"},
                {"rb32"                            , "Possible Defensive Proccess"},
                {"rcsync"                          , "Possible Defensive Proccess"},
                {"realmon"                         , "Possible Defensive Proccess"},
                {"reged"                           , "Possible Defensive Proccess"},
                {"regedit"                         , "REGISTRY EDITOR"},
                {"regedt32"                        , "REGISTRY EDITOR"},
                {"rescue"                          , "Possible Defensive Proccess"},
                {"rescue32"                        , "Possible Defensive Proccess"},
                {"rrguard"                         , "Possible Defensive Proccess"},
                {"rtvscan"                         , "Possible Defensive Proccess"},
                {"rtvscn95"                        , "Possible Defensive Proccess"},
                {"rulaunch"                        , "Possible Defensive Proccess"},
                {"run32dll"                        , "Possible Defensive Proccess"},
                {"rundll"                          , "Possible Defensive Proccess"},
                {"rundll16"                        , "Possible Defensive Proccess"},
                {"ruxdll32"                        , "Possible Defensive Proccess"},
                {"safeweb"                         , "Possible Defensive Proccess"},
                {"sahagentscan32"                  , "Possible Defensive Proccess"},
                {"save"                            , "Possible Defensive Proccess"},
                {"savenow"                         , "Possible Defensive Proccess"},
                {"sbserv"                          , "Possible Defensive Proccess"},
                {"scam32"                          , "Possible Defensive Proccess"},
                {"scan32"                          , "Possible Defensive Proccess"},
                {"scan95"                          , "Possible Defensive Proccess"},
                {"scanpm"                          , "Possible Defensive Proccess"},
                {"scrscan"                         , "Possible Defensive Proccess"},
                {"SentinelOne"                     , "Possible Defensive Proccess"},
                {"serv95"                          , "Possible Defensive Proccess"},
                {"setupvameeval"                   , "Possible Defensive Proccess"},
                {"setup_flowprotector_us"          , "Possible Defensive Proccess"},
                {"sfc"                             , "Possible Defensive Proccess"},
                {"sgssfw32"                        , "Possible Defensive Proccess"},
                {"sh"                              , "Possible Defensive Proccess"},
                {"shellspyinstall"                 , "Possible Defensive Proccess"},
                {"shn"                             , "Possible Defensive Proccess"},
                {"showbehind"                      , "Possible Defensive Proccess"},
                {"shstat"                          , "McAfee VirusScan Enterprise"},
                {"SISIDSService"                   , "Possible Defensive Proccess"},
                {"SISIPSUtil"                      , "Possible Defensive Proccess"},
                {"smc"                             , "Possible Defensive Proccess"},
                {"sms"                             , "Possible Defensive Proccess"},
                {"smss32"                          , "Possible Defensive Proccess"},
                {"soap"                            , "Possible Defensive Proccess"},
                {"sofi"                            , "Possible Defensive Proccess"},
                {"sperm"                           , "Possible Defensive Proccess"},
                {"splunk"                          , "Splunk"},
                {"splunkd"                         , "Splunk"},
                {"splunk-admon"                    , "Splunk"},
                {"splunk-powershell"               , "Splunk"},
                {"splunk-winevtlog"                , "Splunk"},
                {"spf"                             , "Possible Defensive Proccess"},
                {"sphinx"                          , "Possible Defensive Proccess"},
                {"spoler"                          , "Possible Defensive Proccess"},
                {"spoolcv"                         , "Possible Defensive Proccess"},
                {"spoolsv32"                       , "Possible Defensive Proccess"},
                {"spyxx"                           , "Possible Defensive Proccess"},
                {"srexe"                           , "Possible Defensive Proccess"},
                {"srng"                            , "Possible Defensive Proccess"},
                {"ss3edit"                         , "Possible Defensive Proccess"},
                {"ssgrate"                         , "Possible Defensive Proccess"},
                {"ssg_4104"                        , "Possible Defensive Proccess"},
                {"st2"                             , "Possible Defensive Proccess"},
                {"start"                           , "Possible Defensive Proccess"},
                {"stcloader"                       , "Possible Defensive Proccess"},
                {"supftrl"                         , "Possible Defensive Proccess"},
                {"support"                         , "Possible Defensive Proccess"},
                {"supporter5"                      , "Possible Defensive Proccess"},
                {"svchostc"                        , "Possible Defensive Proccess"},
                {"svchosts"                        , "Possible Defensive Proccess"},
                {"sweep95"                         , "Possible Defensive Proccess"},
                {"sweepnet.sweepsrv.sys.swnetsup"  , "Possible Defensive Proccess"},
                {"symproxysvc"                     , "Possible Defensive Proccess"},
                {"symtray"                         , "Possible Defensive Proccess"},
                {"sysedit"                         , "Possible Defensive Proccess"},
                {"sysmon"                          , "Sysinternals Sysmon"},
                {"sysupd"                          , "Possible Defensive Proccess"},
                {"TaniumClient"                    , "Tanium"},
                {"taskmg"                          , "Possible Defensive Proccess"},
                {"taskmo"                          , "Possible Defensive Proccess"},
                {"taumon"                          , "Possible Defensive Proccess"},
                {"tbmon"                           , "Possible Defensive Proccess"},
                {"tbscan"                          , "Possible Defensive Proccess"},
                {"tc"                              , "Possible Defensive Proccess"},
                {"tca"                             , "Possible Defensive Proccess"},
                {"tcm"                             , "Possible Defensive Proccess"},
                {"tcpview"                         , "Possible Defensive Proccess"},
                {"tds-3"                           , "Possible Defensive Proccess"},
                {"tds2-98"                         , "Possible Defensive Proccess"},
                {"tds2-nt"                         , "Possible Defensive Proccess"},
                {"teekids"                         , "Possible Defensive Proccess"},
                {"tfak"                            , "Possible Defensive Proccess"},
                {"tfak5"                           , "Possible Defensive Proccess"},
                {"tgbob"                           , "Possible Defensive Proccess"},
                {"titanin"                         , "Possible Defensive Proccess"},
                {"titaninxp"                       , "Possible Defensive Proccess"},
                {"tlaservice"                      , "Possible Defensive Proccess"},
                {"tlaworker"                       , "Possible Defensive Proccess"},
                {"tracert"                         , "Possible Defensive Proccess"},
                {"trickler"                        , "Possible Defensive Proccess"},
                {"trjscan"                         , "Possible Defensive Proccess"},
                {"trjsetup"                        , "Possible Defensive Proccess"},
                {"trojantrap3"                     , "Possible Defensive Proccess"},
                {"tsadbot"                         , "Possible Defensive Proccess"},
                {"tshark"                          , "Possible Defensive Proccess"},
                {"tvmd"                            , "Possible Defensive Proccess"},
                {"tvtmd"                           , "Possible Defensive Proccess"},
                {"udaterui"                        , "Possible Defensive Proccess"},
                {"undoboot"                        , "Possible Defensive Proccess"},
                {"updat"                           , "Possible Defensive Proccess"},
                {"update"                          , "Possible Defensive Proccess"},
                {"updaterui"                       , "Possible Defensive Proccess"},
                {"upgrad"                          , "Possible Defensive Proccess"},
                {"utpost"                          , "Possible Defensive Proccess"},
                {"vbcmserv"                        , "Possible Defensive Proccess"},
                {"vbcons"                          , "Possible Defensive Proccess"},
                {"vbust"                           , "Possible Defensive Proccess"},
                {"vbwin9x"                         , "Possible Defensive Proccess"},
                {"vbwinntw"                        , "Possible Defensive Proccess"},
                {"vcsetup"                         , "Possible Defensive Proccess"},
                {"vet32"                           , "Possible Defensive Proccess"},
                {"vet95"                           , "Possible Defensive Proccess"},
                {"vettray"                         , "Possible Defensive Proccess"},
                {"vfsetup"                         , "Possible Defensive Proccess"},
                {"vir-help"                        , "Possible Defensive Proccess"},
                {"virusmdpersonalfirewall"         , "Possible Defensive Proccess"},
                {"vnlan300"                        , "Possible Defensive Proccess"},
                {"vnpc3000"                        , "Possible Defensive Proccess"},
                {"vpc32"                           , "Possible Defensive Proccess"},
                {"vpc42"                           , "Possible Defensive Proccess"},
                {"vpfw30s"                         , "Possible Defensive Proccess"},
                {"vptray"                          , "Possible Defensive Proccess"},
                {"vscan40"                         , "Possible Defensive Proccess"},
                {"vscenu6.02d30"                   , "Possible Defensive Proccess"},
                {"vsched"                          , "Possible Defensive Proccess"},
                {"vsecomr"                         , "Possible Defensive Proccess"},
                {"vshwin32"                        , "Possible Defensive Proccess"},
                {"vsisetup"                        , "Possible Defensive Proccess"},
                {"vsmain"                          , "Possible Defensive Proccess"},
                {"vsmon"                           , "Possible Defensive Proccess"},
                {"vsstat"                          , "Possible Defensive Proccess"},
                {"vstskmgr"                        , "McAfee VirusScan Enterprise"},
                {"vswin9xe"                        , "Possible Defensive Proccess"},
                {"vswinntse"                       , "Possible Defensive Proccess"},
                {"vswinperse"                      , "Possible Defensive Proccess"},
                {"w32dsm89"                        , "Possible Defensive Proccess"},
                {"w9x"                             , "Possible Defensive Proccess"},
                {"watchdog"                        , "Possible Defensive Proccess"},
                {"webdav"                          , "Possible Defensive Proccess"},
                {"webscanx"                        , "Possible Defensive Proccess"},
                {"webtrap"                         , "Possible Defensive Proccess"},
                {"wfindv32"                        , "Possible Defensive Proccess"},
                {"whoswatchingme"                  , "Possible Defensive Proccess"},
                {"wimmun32"                        , "Possible Defensive Proccess"},
                {"win-bugsfix"                     , "Possible Defensive Proccess"},
                {"win32"                           , "Possible Defensive Proccess"},
                {"win32us"                         , "Possible Defensive Proccess"},
                {"winactive"                       , "Possible Defensive Proccess"},
                {"window"                          , "Possible Defensive Proccess"},
                {"windows"                         , "Possible Defensive Proccess"},
                {"wininetd"                        , "Possible Defensive Proccess"},
                {"wininitx"                        , "Possible Defensive Proccess"},
                {"winmain"                         , "Possible Defensive Proccess"},
                {"winnet"                          , "Possible Defensive Proccess"},
                {"winppr32"                        , "Possible Defensive Proccess"},
                {"winrecon"                        , "Possible Defensive Proccess"},
                {"winservn"                        , "Possible Defensive Proccess"},
                {"winssk32"                        , "Possible Defensive Proccess"},
                {"winstart"                        , "Possible Defensive Proccess"},
                {"winstart001"                     , "Possible Defensive Proccess"},
                {"wintsk32"                        , "Possible Defensive Proccess"},
                {"winupdate"                       , "Possible Defensive Proccess"},
                {"wireshark"                       , "Possible Defensive Proccess"},
                {"wkufind"                         , "Possible Defensive Proccess"},
                {"wnad"                            , "Possible Defensive Proccess"},
                {"wnt"                             , "Possible Defensive Proccess"},
                {"wradmin"                         , "Possible Defensive Proccess"},
                {"wrctrl"                          , "Possible Defensive Proccess"},
                {"wsbgate"                         , "Possible Defensive Proccess"},
                {"wupdater"                        , "Possible Defensive Proccess"},
                {"wupdt"                           , "Possible Defensive Proccess"},
                {"wyvernworksfirewall"             , "Possible Defensive Proccess"},
                {"xagt"                            , "Possible Defensive Proccess"},
                {"xpf202en"                        , "Possible Defensive Proccess"},
                {"zapro"                           , "Possible Defensive Proccess"},
                {"zapsetup3001"                    , "Possible Defensive Proccess"},
                {"zatutor"                         , "Possible Defensive Proccess"},
                {"zonalm2601"                      , "Possible Defensive Proccess"},
                {"zonealarm"                       , "Possible Defensive Proccess"},
                {"_avp32"                          , "Possible Defensive Proccess"},
                {"_avpcc"                          , "Possible Defensive Proccess"},
                {"rshell"                          , "Possible Defensive Proccess"},
                {"_avpm"                           , "Possible Defensive Proccess"},
                {"chrome"                          , "Google Chrome"},
                {"iexplore"                        , "Microsoft Internet Explorer"},
                {"MicrosoftEdge"                   , "Microsoft Edge"},
                {"firefox"                         , "Mozilla Firefox"},
                {"CmRcService"                     , "Configuration Manager Remote Control Service"},
                {"ftp"                             , "Misc. FTP client"},
                {"LMIGuardian"                     , "LogMeIn Reporter"},
                {"LogMeInSystray"                  , "LogMeIn System Tray"},
                {"RaMaint"                         , "LogMeIn maintenance sevice"},
                {"mmc"                             , "Microsoft Management Console"},
                {"putty"                           , "Putty SSH client"},
                {"pscp"                            , "Putty SCP client"},
                {"psftp"                           , "Putty SFTP client"},
                {"puttytel"                        , "Putty Telnet client"},
                {"plink"                           , "Putty CLI client"},
                {"pageant"                         , "Putty SSH auth agent"},
                {"kitty"                           , "Kitty SSH client"},
                {"telnet"                          , "Misc. Telnet client"},
                {"SecureCRT"                       , "SecureCRT SSH/Telnet client"},
                {"TeamViewer"                      , "TeamViewer"},
                {"tv_x64"                          , "TeamViewer x64 remote control"},
                {"tv_w32"                          , "TeamViewer x86 remote control"},
                {"keepass"                         , "KeePass password vault"},
                {"mstsc"                           , "Microsoft RDP client"},
                {"vnc"                             , "Possible VNC client"},
                {"powershell"                      , "PowerShell host process"},
                {"cmd"                             , "Command Prompt"},
            };

    }
}
